before:
  hooks:
    - go mod tidy
builds:
  - id: wins
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    binary: wins
    main: cmd/main.go
    ldflags:
      - -s -w -X github.com/rancher/wins/pkg/defaults.AppVersion={{.Version}} -X github.com/rancher/wins/pkg/defaults.AppCommit={{.Commit}} -extldflags "-static"
  - id: wins-container
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    binary: wins-container
    main: cmd/main.go
    ldflags:
      - -s -w -X github.com/rancher/wins/pkg/defaults.AppVersion={{.Version}} -X github.com/rancher/wins/pkg/defaults.AppCommit=container -extldflags "-static"

checksum:
  name_template: 'sha256sum.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^tests:'
      - '^scripts:'
